description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  # name: V100-32G
  name: V100-32G-sc

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  # local_dir: /D_data/kaqiu/cifar10/
  # remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  local_dir: /D_data/kaqiu/ti500k
  remote_dir: ti500k/

jobs:
# - name: pt_ti500k_r152_n025_coslr1_e100
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/ti500k/r152_n025_coslr1_e100.json
#   process_count_per_node: 8
# - name: ft_r152_ti500kn025lr01e100_coslr0001_bs128_n025_e100_P100
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r152_ti500kn025lr01e100_coslr0001_bs128_n025_e100.json
# - name: pt_imgn32_r300_n025_coslr01_e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/r300_n025_coslr01_e100.json
#   process_count_per_node: 8
# - name: pt_imgn32_r152w2_n025_coslr1_e100
#   sku: 32xG4-P100
#   command:
#   - python train.py --config configs/imagenet32/r152w2_n025_coslr1_e100.json
#   process_count_per_node: 4
# - name: ft_r152_ti500kn025lr01e800_coslr001_bs128_n025_e40
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r152_ti500kn025lr01e800_coslr001_bs128_n025_e40.json
# - name: ft_r152_ti500kn025lr01e800_coslr001_bs128_n025_e100_P100
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r152_ti500kn025lr01e800_coslr001_bs128_n025_e100.json
# - name: ft_r300_imgn32n025e100_coslr01_bs128_n025_e40
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr01_bs128_n025_e40.json
# - name: ft_r300_imgn32n025e100_coslr001_bs128_n025_e40
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr001_bs128_n025_e40.json
# - name: ft_r300_imgn32n025e100_coslr0001_bs128_n025_e40
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr0001_bs128_n025_e40.json
# - name: ft_r300_imgn32n025e100_coslr01_bs128_n025_e100
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr01_bs128_n025_e100.json
# - name: ft_r300_imgn32n025e100_coslr001_bs128_n025_e100
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr001_bs128_n025_e100.json
# - name: ft_r300_imgn32n025e100_coslr0001_bs128_n025_e100
#   sku: G4
#   command:
#   - python train.py --config configs/finetune/r300_imgn32n025e100_coslr0001_bs128_n025_e100.json
# - name: pt_imgn32_r152w2_n025_coslr1_e100_V100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/r152w2_n025_coslr1_e100.json
#   process_count_per_node: 8
# - name: pt_imgn32_r300_n025_coslr01_e200
#   sku: 32xG4-P100
#   command:
#   - python train.py --config configs/imagenet32/r300_n025_coslr01_e200.json
#   process_count_per_node: 4
# - name: pt_imgn32_r152w2_n025_coslr01_e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/r152w2_n025_coslr01_e100.json
#   process_count_per_node: 8
# - name: pt_moco_r152_2crop_e100_croppad32
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2crop_e100.json
#   process_count_per_node: 4
# - name: pt_moco_r152_cropn025_e100
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_cropn025_e100.json
#   process_count_per_node: 4
# - name: pt_moco_r152_2noise025_e100
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2noise025_e100.json
#   process_count_per_node: 4
# - name: pt_moco_r152_2onlynoise025_e100
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2onlynoise025_e100.json
#   process_count_per_node: 4
# - name: pt_moco_r152_2crop_e100_lr006
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2crop_e100_lr006.json
#   process_count_per_node: 4
# - name: pt_moco_r152_2noise025_e100_lr006
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2noise025_e100_lr006.json
#   process_count_per_node: 4
# - name: pt_moco_r152_2onlynoise025_e100_lr006
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_2onlynoise025_e100_lr006.json
#   process_count_per_node: 4
# - name: pt_moco_r152_cropn025_e100_lr006
#   sku: 8xG4-P100
#   command:
#   - python train.py --config configs/moco/r152_cropn025_e100_lr006.json
#   process_count_per_node: 4
# - name: pt_moco_ti500k_nmr152_2crop_e100
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_2crop_e100.json
#   # process_count_per_node: 4
# - name: pt_moco_ti500k_nmr152_2noise025_e100
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_2noise025_e100.json
#   # process_count_per_node: 4
# - name: pt_moco_ti500k_nmr152_2onlynoise025_e100
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_2onlynoise025_e100.json
#   # process_count_per_node: 4
# - name: pt_moco_ti500k_nmr152_cropn025_e100
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_cropn025_e100.json
#   # process_count_per_node: 4
# - name: pt_moco_ti500k_nmr152_cropn025_e200
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_cropn025_e200.json
#   process_count_per_node: 8
# - name: pt_moco_ti500k_nmr152_1crop2noise_e100
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/ti500k_nmr152_1crop2noise_e100.json
#   # process_count_per_node: 4
# - name: pt_moco_nmr152_1crop2noise_e100_lr006
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_1crop2noise_e100_lr006.json
#   # process_count_per_node: 4
# - name: pt_moco_nmr152_2crop_e100_lr006
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_2crop_e100_lr006.json
#   # process_count_per_node: 4
# - name: pt_moco_nmr152_2noise025_e100_lr006
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_2noise025_e100_lr006.json
  # process_count_per_node: 4
# - name: pt_moco_nmr152_2onlynoise025_e100_lr006
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_2onlynoise025_e100_lr006.json
#   # process_count_per_node: 4
# - name: pt_moco_nmr152_cropn025_e100_lr006
#   sku: 1xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_cropn025_e100_lr006.json
#   # process_count_per_node: 4
# - name: pt_moco_nmr152_cropn025_e200_lr006
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/moco/nmr152_cropn025_e200_lr006.json
#   process_count_per_node: 8
- name: pt_moco_ti500k_nmr152_2crop_e100_lr006
  sku: 1xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_2crop_e100_lr006.json
  # process_count_per_node: 4
- name: pt_moco_ti500k_nmr152_2noise025_e100_lr006
  sku: 1xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_2noise025_e100_lr006.json
  # process_count_per_node: 4
- name: pt_moco_ti500k_nmr152_2onlynoise025_e100_lr006
  sku: 1xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_2onlynoise025_e100_lr006.json
  # process_count_per_node: 4
- name: pt_moco_ti500k_nmr152_cropn025_e100_lr006
  sku: 1xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_cropn025_e100_lr006.json
  # process_count_per_node: 4
- name: pt_moco_ti500k_nmr152_cropn025_e200_lr006
  sku: 2xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_cropn025_e200_lr006.json
  process_count_per_node: 8
- name: pt_moco_ti500k_nmr152_1crop2noise_e100_lr006
  sku: 1xG8-V100
  command:
  - python train.py --config configs/moco/ti500k_nmr152_1crop2noise_e100_lr006.json
  # process_count_per_node: 4