description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  service: sing
  name: msrresrchvc

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

# storage:
#   my_output:
#     storage_account_name: West US 2
#     container_name: kaqiu
#     mount_dir: kaqiu/projects/amlt_local/smoothing/
#     local_dir: $CONFIG_DIR/amlt/smoothing/

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/

jobs:
- name: r110_n025_coslr01_bs128_e51200_v2
  sku: 2xG8
  process_count_per_node: 8
  command:
  - python train.py --config resnet110/n025_coslr01_bs128_e51200_v2.json
- name: r110_n025_coslr01_bs128_e102400_v2
  sku: 2xG8
  process_count_per_node: 8
  command:
  - python train.py --config resnet110/n025_coslr01_bs128_e102400_v2.json
