description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  name: V100-32G
  # name: V100-32G-sc  
  # name: A100-80G

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install transformers
  - pip install timm

code:
  local_dir: $CONFIG_DIR/code

data:
  local_dir: /D_data/kaqiu/imagenet/
  remote_dir: imagenet/
  # local_dir: /D_data/kaqiu/cifar10/
  # remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/  

jobs:
# - name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
#   sku: 2xG8-A100
#   command:
#   - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
#   process_count_per_node: 8
# - name: vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100_ctf_224n
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100_ctf_224n.json
# - name: dif_vit_in21k_ft_cf10_adam1e_2_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam1e_2_e100.json
# - name: dif_vit_in21k_ft_cf10_adam1e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam1e_3_e100.json
# - name: dif_vit_in21k_ft_cf10_adam1e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam1e_4_e100.json
# - name: dif_vit_in21k_ft_cf10_adam5e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam5e_3_e100.json
# - name: dif_vit_in21k_ft_cf10_adam5e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam5e_4_e100.json
# - name: dif_vit_in21k_ft_cf10_adam5e_5_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam5e_5_e100.json
# - name: dif_vit_in21k_ft_cf10_ctf
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_ctf.json
# - name: dif_vit_in21k_ft_cf10_adam1e_4_e10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam1e_4_e10.json
# - name: dif_vit_in21k_ft_cf10_adam1e_4_e50
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_adam1e_4_e50.json
# - name: dif_vit_in21k_ft_cf10_ctf_full
#   sku: G8-V100
#   command:
#   - python train.py --config configs/diffusion/dif_vit_in21k_ft_cf10_ctf_full.json
# - name: vit_224_in21k_ft_cf10_ctf
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_ctf.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e1
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e1.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e2
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e2.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e3
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e3.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e4
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e4.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e5
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e5.json
# - name: r152_imgn32n025e100_coslr001_bs128_n025_e100_full_ctf
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/r152_imgn32n025e100_coslr001_bs128_n025_e100_full_ctf.json
# - name: in_r152_n025_lr1_bs16_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs16_e100.json
# - name: in_r152_n025_lr01_bs16_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr01_bs16_e100.json
# - name: in_r152_n025_lr001_bs16_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr001_bs16_e100.json
# - name: in_r152_n025_lr0001_bs16_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr0001_bs16_e100.json
# - name: in_r152_n025_lr00001_bs16_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr00001_bs16_e100.json
# - name: in_r152_n025_lr1_bs32_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs32_e100.json
# - name: in_r152_n025_lr01_bs32_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr01_bs32_e100.json
# - name: in_r152_n025_lr001_bs32_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr001_bs32_e100.json
# - name: in_r152_n025_lr0001_bs32_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr0001_bs32_e100.json
# - name: in_r152_n025_lr00001_bs32_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr00001_bs32_e100.json
# - name: r152_n025_lr1_bs64_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs64_e100.json
# - name: r152_n025_lr1_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs128_e100.json
# - name: r152_n025_lr1_bs256_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs256_e100.json
# - name: r152_n025_lr1_bs512_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet/r152_n025_lr1_bs512_e100.json
- name: r152_n025_lr01_bs256_e100
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet/r152_n025_lr01_bs256_e100.json
- name: r152_n025_lr001_bs256_e100
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet/r152_n025_lr001_bs256_e100.json
- name: r152_n025_lr0001_bs256_e100
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet/r152_n025_lr0001_bs256_e100.json
- name: r152_n025_lr00001_bs256_e100
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet/r152_n025_lr00001_bs256_e100.json