description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  # name: V100-32G
  name: V100-32G-sc  
  # name: A100-80G

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install transformers

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/  

jobs:
# - name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
#   sku: 2xG8-A100
#   command:
#   - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
#   process_count_per_node: 8
# - name: nconv_fn01a8_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a8_gn025_lr01_e100.json
# - name: nconv_fn01a16_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a16_gn025_lr01_e100.json
# - name: nconv_fn01a32_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a32_gn025_lr01_e100.json
# - name: nconv_fn005a8_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn005a8_gn025_lr01_e100.json
# - name: nconv_fn005a16_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn005a16_gn025_lr01_e100.json
# - name: nconv_fn005a32_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn005a32_gn025_lr01_e100.json
# - name: nconv_fn01a8_gn025_lr01_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a8_gn025_lr01_e800.json
# - name: nconv_fn01a8_gn025_lr01_e1600
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a8_gn025_lr01_e1600.json
# - name: nconv_fn01a16_gn025_lr01_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a16_gn025_lr01_e800.json
# - name: nconv_fn01a16_gn025_lr01_e1600
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a16_gn025_lr01_e1600.json
# - name: nconv_fn01a32_gn025_lr01_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a32_gn025_lr01_e800.json
# - name: nconv_fn01a32_gn025_lr01_e1600
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a32_gn025_lr01_e1600.json
# - name: nconv_fn01a8_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a8_gn025_lr001_e100.json
# - name: nconv_fn01a2_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a2_gn025_lr01_e100.json
# - name: nconv_fn01a4_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a4_gn025_lr01_e100.json
# - name: nconv_fn005a2_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn005a2_gn025_lr01_e100.json
# - name: nconv_fn005a4_gn025_lr01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn005a4_gn025_lr01_e100.json
# - name: nconv_fn01a2_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a2_gn025_lr001_e100.json
# - name: nconv_fn01a4_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a4_gn025_lr001_e100.json
# - name: nconv_fn01a8_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a8_gn025_lr001_e100.json
# - name: nconv_fn01a16_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a16_gn025_lr001_e100.json
# - name: nconv_fn01a32_gn025_lr001_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/nconv_fn01a32_gn025_lr001_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_2_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_2_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_3_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_5_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_5_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_6_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_6_e100.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e5
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e5.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e10.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e50
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e50.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e100.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e200.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e400.json
# - name: vit_224_in21k_ft_cf10_adam5e_5_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam5e_5_e800.json
# - name: vit_224_in21k_ft_cf10_adamw1e_2_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_2_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_3_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_4_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_5_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_5_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_6_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_6_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_2_wd01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_2_wd01_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_3_wd01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_3_wd01_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_4_wd01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_4_wd01_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_5_wd01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_5_wd01_e100.json
# - name: vit_224_in21k_ft_cf10_adamw1e_6_wd01_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adamw1e_6_wd01_e100.json
# - name: bl64_n025_coslr01_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl64_n025_coslr01_bs128_e100.json
# - name: bl128_n025_coslr01_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl128_n025_coslr01_bs128_e100.json
# - name: bl224_n025_coslr01_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl224_n025_coslr01_bs128_e100.json
# - name: bl64_n025_coslr001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl64_n025_coslr001_bs128_e100.json
# - name: bl128_n025_coslr001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl128_n025_coslr001_bs128_e100.json
# - name: bl224_n025_coslr001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl224_n025_coslr001_bs128_e100.json
# - name: bl64_n025_coslr0001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl64_n025_coslr0001_bs128_e100.json
# - name: bl128_n025_coslr0001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl128_n025_coslr0001_bs128_e100.json
# - name: bl224_n025_coslr0001_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/resnet152/bl224_n025_coslr0001_bs128_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam1e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam1e_4_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam5e_4_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam5e_4_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam5e_5_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam5e_5_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam1e_2_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam1e_2_e100.json
# - name: vit_32n_rs224_in21k_ft_cf10_adam5e_3_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam5e_3_e100.json
# - name: vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224
#   sku: G8-V100
#   command:
#   - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224.json
- name: vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100_ctf_224n
  sku: G8-V100
  command:
  - python train.py --config configs/hug/vit_32n_rs224_in21k_ft_cf10_adam1e_3_e100_ctf_224n.json