description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  service: sing
  name: msrresrchvc

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/

jobs:
- name: r110_n025_coslr01_bs128_e200_dav3
  sku: G4
  # process_count_per_node: 8
  command:
  - python train.py --config configs/resnet110/n025_coslr01_bs128_e200_dav3.json
- name: r110_n025_coslr01_bs128_e1600_dav3
  sku: G4
  command:
  - python train.py --config configs/resnet110/n025_coslr01_bs128_e1600_dav3.json
- name: r110_n025_coslr01_bs128_e200_damix
  sku: G4
  command:
  - python train.py --config configs/resnet110/n025_coslr01_bs128_e200_damix.json
- name: r110_n025_coslr01_bs128_e1600_damix
  sku: G4
  command:
  - python train.py --config configs/resnet110/n025_coslr01_bs128_e1600_damix.json
