description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  service: sing
  name: msrresrchvc

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

# storage:
  # input:
  #   storage_account_name: input_storage_account
  #   container_name: amlt
  # output:
  #   storage_account_name: output_storage_account
  #   container_name: kaqiu
  #   mount_dir: /mnt/output
  # external:
  #   storage_account_name: external_storage_account
  #   container_name: dataset
  #   mount_dir: /mnt/shared_data

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/

jobs:
- name: r152_n025_lr01_bs16_e200
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs16_e200.json
- name: r152_n025_lr01_bs16_e400
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs16_e400.json
- name: r152_n025_lr01_bs16_e800
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs16_e800.json
- name: r152_n025_lr01_bs128_e200
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs128_e200.json
- name: r152_n025_lr01_bs128_e400
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs128_e400.json
- name: r152_n025_lr01_bs128_e800
  sku: G4
  command:
  - python train.py --config resnet152/n025_lr01_bs128_e800.json
- name: r152_n025_coslr01_bs16_e200
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs16_e200.json
- name: r152_n025_coslr01_bs16_e400
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs16_e400.json
- name: r152_n025_coslr01_bs16_e800
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs16_e800.json
- name: r152_n025_coslr01_bs128_e200
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs128_e200.json
- name: r152_n025_coslr01_bs128_e400
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs128_e400.json
- name: r152_n025_coslr01_bs128_e800
  sku: G4
  command:
  - python train.py --config resnet152/n025_coslr01_bs128_e800.json
