description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  # name: V100-32G
  name: V100-32G-sc  
  # name: V100-32G-sc2  

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/

jobs:
# - name: mixup_moco_nmrr1522noise025e100_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e100_coslr001_bs128_n025_e100.json
# - name: mixup_moco_nmrr1522noise025e100_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e100_coslr001_bs128_n025_e800.json
# - name: mixup_r152_imgn32n025e100_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_r152_imgn32n025e100_coslr001_bs128_n025_e100.json
# - name: mixup_r152_imgn32n025e100_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_r152_imgn32n025e100_coslr001_bs128_n025_e800.json
# - name: pt_mixup_imgn32_r152_n025_coslr1_e100
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/mixup_r152_n025_coslr1_e100.json
#   process_count_per_node: 8
# - name: pt_mixup_imgn32_r152_n025_coslr01_e100
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/mixup_r152_n025_coslr01_e100.json
#   process_count_per_node: 8
# - name: mixup_moco_nmrr1522noise025e200_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e200_coslr001_bs128_n025_e100.json
# - name: mixup_moco_nmrr1522noise025e400_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e400_coslr001_bs128_n025_e100.json
# - name: mixup_moco_nmrr1522noise025e800_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e800_coslr001_bs128_n025_e100.json
# - name: mixup_moco_ti500k_nmrr1522noise025e100_coslr001_bs128_n025_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_ti500k_nmrr1522noise025e100_coslr001_bs128_n025_e100.json
# - name: mixup_moco_nmrr1522noise025e200_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e200_coslr001_bs128_n025_e800.json
# - name: mixup_moco_nmrr1522noise025e400_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e400_coslr001_bs128_n025_e800.json
# - name: mixup_moco_nmrr1522noise025e800_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_nmrr1522noise025e800_coslr001_bs128_n025_e800.json
# - name: mixup_moco_ti500k_nmrr1522noise025e100_coslr001_bs128_n025_e800
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/mixup_moco_ti500k_nmrr1522noise025e100_coslr001_bs128_n025_e800.jsond
- name: mixup_r152_imgn32n025e100mixup_coslr001_bs128_n025_e100
  sku: G8-V100
  command:
  - python train.py --config configs/finetune/mixup_r152_imgn32n025e100mixup_coslr001_bs128_n025_e100.json
- name: mixup_r152_imgn32n025e100mixup_coslr001_bs128_n025_e800
  sku: G8-V100
  command:
  - python train.py --config configs/finetune/mixup_r152_imgn32n025e100mixup_coslr001_bs128_n025_e800.json
