description: My Project

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  service: sing
  name: msrresrchvc

environment:
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install transformers
  - pip install timm

code:
  local_dir: $CONFIG_DIR/code

data:
  local_dir: /D_data/kaqiu/imagenet/
  remote_dir: imagenet/

jobs:
- name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
  sku: 2xG8-V100
  command:
  - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
  process_count_per_node: 8
- name: vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224
  sku: G8-V100
  command:
  - python train.py --config configs/hug/vit_224_in21k_ft_cf10_adam1e_4_e100_ctf_32n_rs224.json