description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  service: sing
  name: msrresrchvc

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/

jobs:
# - name: pt_imgn32_r152_n025_coslr1_e400_m16
#   sku: 16xG4
#   command:
#   - python train.py --config configs/imagenet32/r152_n025_coslr1_e400.json
#   process_count_per_node: 4
- name: ft_r152_imgn32n025e200_coslr001_bs128_n025_e40
  sku: G4
  command:
  - python train.py --config configs/finetune/r152_imgn32n025e200_coslr001_bs128_n025_e40.json
- name: ft_r152_imgn32n025e200_coslr001_bs128_n025_e100
  sku: G4
  command:
  - python train.py --config configs/finetune/r152_imgn32n025e200_coslr001_bs128_n025_e100.json
- name: ft_r152_imgn32n025e400_coslr001_bs128_n025_e40
  sku: G4
  command:
  - python train.py --config configs/finetune/r152_imgn32n025e400_coslr001_bs128_n025_e40.json
- name: ft_r152_imgn32n025e400_coslr001_bs128_n025_e100
  sku: G4
  command:
  - python train.py --config configs/finetune/r152_imgn32n025e400_coslr001_bs128_n025_e100.json