description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  name: V100-32G
  # name: V100-32G-sc  
  # name: A100-80G
  # name: ussc40rscl

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install torchvision==0.13.1
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install transformers
  - pip install timm

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  # local_dir: /D_data/kaqiu/cifar10/
  # remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/
  # all datasets
  local_dir: /D_data/kaqiu/
  remote_dir: datasets/

jobs:
# - name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
#   sku: 2xG8-A100
#   command:
#   - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
#   process_count_per_node: 8
#   mpi: true
# - name: nemb_all_rnsd1_s1_r152_lr01_bs128_e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/nemb/nemb_all_rnsd1_s1_r152_lr01_bs128_e100.json


# - name: nep_n025n05n1_cln_cls_kl1_bfc_fzc_r152gn1_in32bs128_lr01e800
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_n025n05n1_cln_cls_kl1_bfc_fzc_r152gn1_in32bs128_lr01e800.json
#   process_count_per_node: 8
#   mpi: true
# - name: nep_n025n05n1_cln_cls_kl1_bfc_fzc_r152gn1_in32bs128_lr01e1600
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_n025n05n1_cln_cls_kl1_bfc_fzc_r152gn1_in32bs128_lr01e1600.json
#   process_count_per_node: 8
#   mpi: true

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e800
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r152gn1_in32n0n025n05n1bs128_lr01e800.json
#   process_count_per_node: 8
#   mpi: true
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e1600
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r152gn1_in32n0n025n05n1bs128_lr01e1600.json
#   process_count_per_node: 8
#   mpi: true

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep100.json
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep100.json

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep200.json
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep200.json

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep400
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep400.json
#   process_count_per_node: 8
#   mpi: true
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep400
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep400.json
#   process_count_per_node: 8
#   mpi: true

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep800
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep800.json
#   process_count_per_node: 8
#   mpi: true
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep800
#   sku: 2xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep800.json
#   process_count_per_node: 8
#   mpi: true

# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep1600
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr001ep1600.json
#   process_count_per_node: 8
#   mpi: true
# - name: nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep1600
#   sku: 4xG8-V100
#   command:
#   - python train.py --config configs/finetune/nep_r152gn1_in32n0n025n05n1bs128_lr01e400_ft_lr0001ep1600.json
#   process_count_per_node: 8
#   mpi: true

# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr1e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr1e100_tfc.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr01e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr01e100_tfc.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr001e100_tfc.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr0001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr0001e100_tfc.json

# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr1e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr1e100.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr01e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr01e100.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr001e100.json
# - name: moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr0001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr10e100_ft_cifar10_n0_lr0001e100.json



# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr1e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr1e100_tfc.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e100_tfc.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e100_tfc.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e100_tfc.json

# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr1e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr1e100.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e100.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e100.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e100.json


# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e200.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e200.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e200.json

# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr01e400.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr001e400.json
# - name: moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/moco_152gn1_nep_lr1e100_ft_cifar10_n0_lr0001e400.json


# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep1_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep1_tfc.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep1_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep1_tfc.json

# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep10_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep10_tfc.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep10_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep10_tfc.json

# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep100_tfc.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep100_tfc.json


# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep1
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep1.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep1
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep1.json

# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep10.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep10.json

# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr001ep100.json
# - name: in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in32_r152gn1_n0_lr01e100_ft_cifar10_nep_n0n025n05n1_lr0001ep100.json


# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e1_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e1_tfc.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e1_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e1_tfc.json

# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e10_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e10_tfc.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e10_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e10_tfc.json

# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e100_tfc.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e100_tfc
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e100_tfc.json


# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e1
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e1.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e1
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e1.json

# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e10.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e10
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e10.json

# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr001e100.json
# - name: in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/cifar10/in_tvr152gn1_nep_n0n025n05n1_lr01e100_ft_cifar10_n0_lr0001e100.json