description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  # name: V100-32G
  # name: V100-32G-sc  
  name: A100-80G

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  local_dir: /D_data/kaqiu/cifar10/
  remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/  

jobs:
# - name: imgn22k_r152_n025_coslr01_bs1024_w4_e200
#   sku: 2xG8-A100
#   command:
#   - python train.py --config configs/imagenet22k/imgn22k_r152_n025_coslr01_bs1024_w4_e200.json
#   process_count_per_node: 8
# - name: avgin2_onlyctf
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin2_onlyctf.json
# - name: avgin4_onlyctf
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin4_onlyctf.json
# - name: avgin8_onlyctf
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin8_onlyctf.json
# - name: avgin16_onlyctf
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin16_onlyctf.json
# - name: avgin32_onlyctf
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin32_onlyctf.json
# - name: avgin2_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin2_n025_lr01_e100.json
# - name: avgin4_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin4_n025_lr01_e100.json
# - name: avgin8_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin8_n025_lr01_e100.json
# - name: avgin16_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin16_n025_lr01_e100.json
# - name: avgin32_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin32_n025_lr01_e100.json
# - name: avgin2ctf_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin2ctf_n025_lr01_e100.json
# - name: avgin4ctf_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin4ctf_n025_lr01_e100.json
# - name: avgin8ctf_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin8ctf_n025_lr01_e100.json
# - name: avgin16ctf_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin16ctf_n025_lr01_e100.json
# - name: avgin32ctf_n025_lr01_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/avgin32ctf_n025_lr01_e100.json
# - name: fn1a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn1a2_gn025_lr01_bs128.json
# - name: fn01a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn01a2_gn025_lr01_bs128.json
# - name: fn001a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn001a2_gn025_lr01_bs128.json
# - name: fn0001a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0001a2_gn025_lr01_bs128.json
# - name: fn00001a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn00001a2_gn025_lr01_bs128.json
# - name: fn1a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn1a4_gn025_lr01_bs128.json
# - name: fn01a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn01a4_gn025_lr01_bs128.json
# - name: fn001a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn001a4_gn025_lr01_bs128.json
# - name: fn0001a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0001a4_gn025_lr01_bs128.json
# - name: fn00001a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn00001a4_gn025_lr01_bs128.json
# - name: fn1a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn1a8_gn025_lr01_bs128.json
# - name: fn01a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn01a8_gn025_lr01_bs128.json
# - name: fn001a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn001a8_gn025_lr01_bs128.json
# - name: fn0001a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0001a8_gn025_lr01_bs128.json
# - name: fn00001a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn00001a8_gn025_lr01_bs128.json
# - name: fn1a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn1a16_gn025_lr01_bs64.json
# - name: fn01a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn01a16_gn025_lr01_bs64.json
# - name: fn001a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn001a16_gn025_lr01_bs64.json
# - name: fn0001a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0001a16_gn025_lr01_bs64.json
# - name: fn00001a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn00001a16_gn025_lr01_bs64.json
# - name: fn1a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn1a32_gn025_lr01_bs32.json
# - name: fn01a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn01a32_gn025_lr01_bs32.json
# - name: fn001a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn001a32_gn025_lr01_bs32.json
# - name: fn0001a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0001a32_gn025_lr01_bs32.json
# - name: fn00001a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn00001a32_gn025_lr01_bs32.json
# - name: fn05a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn05a2_gn025_lr01_bs128.json
# - name: fn005a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a2_gn025_lr01_bs128.json
# - name: fn0005a2_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0005a2_gn025_lr01_bs128.json
# - name: fn05a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn05a4_gn025_lr01_bs128.json
# - name: fn005a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a4_gn025_lr01_bs128.json
# - name: fn0005a4_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0005a4_gn025_lr01_bs128.json
# - name: fn05a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn05a8_gn025_lr01_bs128.json
# - name: fn005a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a8_gn025_lr01_bs128.json
# - name: fn0005a8_gn025_lr01_bs128
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0005a8_gn025_lr01_bs128.json
# - name: fn05a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn05a16_gn025_lr01_bs64.json
# - name: fn005a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr01_bs64.json
# - name: fn0005a16_gn025_lr01_bs64
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0005a16_gn025_lr01_bs64.json
# - name: fn05a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn05a32_gn025_lr01_bs32.json
# - name: fn005a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr01_bs32.json
# - name: fn0005a32_gn025_lr01_bs32
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn0005a32_gn025_lr01_bs32.json
# - name: fn005a16_gn025_lr01_e800
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr01_e800.json
# - name: fn005a16_gn025_lr01_e1600
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr01_e1600.json
# - name: fn005a16_gn025_lr001_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr001_e100.json
# - name: fn005a16_gn025_lr001_e800
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr001_e800.json
# - name: fn005a16_gn025_lr001_e1600
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a16_gn025_lr001_e1600.json
# - name: fn005a32_gn025_lr01_e800
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr01_e800.json
# - name: fn005a32_gn025_lr01_e1600
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr01_e1600.json
# - name: fn005a32_gn025_lr001_e100
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr001_e100.json
# - name: fn005a32_gn025_lr001_e800
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr001_e800.json
# - name: fn005a32_gn025_lr001_e1600
#   sku: G8-A100
#   command:
#   - python train.py --config configs/resnet152/fn005a32_gn025_lr001_e1600.json
- name: fn001a16_gn025_lr01_e800
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a16_gn025_lr01_e800.json
- name: fn001a16_gn025_lr01_e1600
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a16_gn025_lr01_e1600.json
- name: fn001a16_gn025_lr001_e100
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a16_gn025_lr001_e100.json
- name: fn001a16_gn025_lr001_e800
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a16_gn025_lr001_e800.json
- name: fn001a16_gn025_lr001_e1600
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a16_gn025_lr001_e1600.json
- name: fn001a32_gn025_lr01_e800
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a32_gn025_lr01_e800.json
- name: fn001a32_gn025_lr01_e1600
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a32_gn025_lr01_e1600.json
- name: fn001a32_gn025_lr001_e100
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a32_gn025_lr001_e100.json
- name: fn001a32_gn025_lr001_e800
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a32_gn025_lr001_e800.json
- name: fn001a32_gn025_lr001_e1600
  sku: G8-A100
  command:
  - python train.py --config configs/resnet152/fn001a32_gn025_lr001_e1600.json