description: Locuslab Smoothing

target:
  # service: amlk8s
  # name: itplabrr1cl1
  # vc: resrchvc

  # service: amlk8s
  # name: ms-shared

  # service: sing
  # name: msrresrchvc

  service: aml
  name: V100-32G
  # name: V100-32G-sc  
  # name: A100-80G
  # name: ussc40rscl

environment:
  # image: amlt-sing/pytorch-1.7.0-cuda11.0-cudnn8-devel
  # image: wuzhiron/pytorch:pytorch1.7-cuda10.1-py37
  image: wuzhiron/pytorch:pytorch1.10.0-cuda11.3-cudnn8-singularity
  setup:
  - pip install torchvision==0.13.1
  - pip install scipy
  - pip install pandas
  - pip install statsmodels
  - pip install matplotlib
  - pip install seaborn
  - pip install setGPU
  - pip install attrdict
  - pip install einops
  - pip install transformers
  - pip install timm

code:
  local_dir: $CONFIG_DIR/code

data:
  # local_dir: /D_data/kaqiu/imagenet/
  # remote_dir: imagenet/
  # local_dir: /D_data/kaqiu/cifar10/
  # remote_dir: cifar/
  # local_dir: /D_data/kaqiu/imagenet32/
  # remote_dir: imagenet32/
  # local_dir: /D_data/kaqiu/ti500k
  # remote_dir: ti500k/
  # local_dir: /D_data/kaqiu/imagenet22k/
  # remote_dir: imagenet22k/
  # all datasets
  local_dir: /D_data/kaqiu/
  remote_dir: datasets/

jobs:

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e100
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e100.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e100
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e100.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e100
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e100.json


# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e200
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e200.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e200
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e200.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e200
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e200.json


# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e400
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr1e400.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e400
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr01e400.json

# - name: nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e400
#   sku: G8-V100
#   command:
#   - python train.py --config code/configs/imagenet32/nep_r110basicgn1_in32n0n025n05n1bs1024_lr001e400.json



# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e100.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e100.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e100
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e100.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e200.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e200.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e200
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e200.json


# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr1e400.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr01e400.json

# - name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e400
#   sku: G8-V100
#   command:
#   - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr001e400.json


- name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e100
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e100.json

- name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e200
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e200.json

- name: nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e400
  sku: G8-V100
  command:
  - python train.py --config configs/imagenet32/nep_r110bottlegn1_in32n0n025n05n1bs1024_lr10e400.json





# - name: vitb8_imgn22k_nep_n0n025n05n1_lr0001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb8_imgn22k_nep_n0n025n05n1_lr0001e100.json
#   process_count_per_node: 8
#   mpi: true


# - name: vitb8_imgn22k_nep_n0n025n05n1_lr00001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb8_imgn22k_nep_n0n025n05n1_lr00001e100.json
#   process_count_per_node: 8
#   mpi: true


# - name: vitb16_imgn22k_nep_n0n025n05n1_lr0001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb16_imgn22k_nep_n0n025n05n1_lr0001e100.json
#   process_count_per_node: 8
#   mpi: true


# - name: vitb16_imgn22k_nep_n0n025n05n1_lr00001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb16_imgn22k_nep_n0n025n05n1_lr00001e100.json
#   process_count_per_node: 8
#   mpi: true


# - name: vitb8_imgn22k_nep_n0n025n05n1_lr001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb8_imgn22k_nep_n0n025n05n1_lr001e100.json
#   process_count_per_node: 8
#   mpi: true


# - name: vitb4_imgn22k_nep_n0n025n05n1_lr001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb4_imgn22k_nep_n0n025n05n1_lr001e100.json
#   process_count_per_node: 8
#   mpi: true

# - name: vitb4_imgn22k_nep_n0n025n05n1_lr0001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb4_imgn22k_nep_n0n025n05n1_lr0001e100.json
#   process_count_per_node: 8
#   mpi: true

# - name: vitb4_imgn22k_nep_n0n025n05n1_lr00001e100
#   sku: 4xG8-V100
#   command:
#   - python train.py --config code/configs/vit/vitb4_imgn22k_nep_n0n025n05n1_lr00001e100.json
#   process_count_per_node: 8
#   mpi: true